---
version: 0.0
os: linux
files:
  - source: requirements.txt
    destination: /app/
  - source: recipes/
    destination: /app/recipes/
  - source: scripts/
    destination: /app/scripts/
  - source: src/
    destination: /app/src/
  - source: cocktails.service
    destination: /app
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/setup_ec2.sh
    - location: scripts/setup.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
