version: 0.0
os: linux
files:
  - source: requirements.txt
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
    - location: scripts/setup.sh
      timeout: 120
      runas: root
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root

