version: 0.0
os: linux
files:
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 180
      runas: root
    - location: scripts/start_server
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 120
      runas: root

