name: CI

on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; mypy --install-types --non-interactive fi
    - name: flake8
      run: flake8 src --max-line-length=120 --show-source --statistics
    - name: pylint
      run: pylint ./src --rcfile=.pylintrc
    - name: mypy
      run: mypy ./src --config-file=mypy.ini --strict